### ISSUE TITLE
Dataset and data preparation

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [GewelsJI/Hybrid-Eloss#2]
Hello, i want to try it but link paper, the data set download link and three links in data preparation cannot be opened or be expired?

**Comment by GewelsJI** [comment]
Hi, @trinh-hoang-hiep 

Thanks for your note. The latest download links have been updated here: https://github.com/GewelsJI/Hybrid-Eloss#data-preparation

Best,
Ge-Peng.
